# Generated by Django 5.2.5 on 2026-02-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_category_remove_place_category_place_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
