# Generated by Django 5.2.5 on 2025-09-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_badge_challenge_expertarea_comment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_digest',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='safety_rating',
            field=models.IntegerField(choices=[(1, '⭐ Very Unsafe'), (2, '⭐⭐ Unsafe'), (3, '⭐⭐⭐ Neutral'), (4, '⭐⭐⭐⭐ Safe'), (5, '⭐⭐⭐⭐⭐ Very Safe')], default=3),
        ),
    ]
