# Generated by Django 5.2.5 on 2025-09-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_userprofile_allow_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='category_icon',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('place_added', 'Place Added'), ('place_approved', 'Place Approved'), ('place_rejected', 'Place Rejected'), ('comment_reply', 'Comment Reply'), ('nearby_place', 'Nearby Place'), ('challenge', 'Challenge'), ('badge_earned', 'Badge Earned'), ('welcome', 'Welcome')], max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('buddhist_temple', 'Buddhist Temple'), ('hindu_temple', 'Hindu Temple'), ('mosque', 'Islam Mosque'), ('church', 'Christian Church'), ('gurdwara', 'Sikh Gurdwara'), ('synagogue', 'Jewish Synagogue'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
