# Generated by Django 5.2.5 on 2026-02-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='report',
            name='place',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='placecollection',
            name='category',
        ),
        migrations.DeleteModel(
            name='AudioGuide',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='placecollection',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='collections', to='places.category'),
        ),
    ]
