# Generated by Django 5.2.5 on 2025-09-21 08:27

import django.db.models.deletion
import places.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_category_icon_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='comment',
            name='checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='places.checkin'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='photo_proof',
            field=models.ImageField(blank=True, null=True, upload_to=places.models.checkin_photo_upload_to),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=places.models.place_image_upload_to),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to=places.models.place_image_upload_to),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=places.models.user_avatar_upload_to),
        ),
    ]
