# Generated by Django 5.2.5 on 2026-02-19 15:42

import places.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=places.models.badge_image_upload_to),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
