# Generated by Django 5.2.5 on 2025-09-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placecollection',
            name='category',
            field=models.CharField(choices=[('buddhist_temple', 'Buddhist Temple'), ('hindu_temple', 'Hindu Temple'), ('mosque', 'Islam Mosque'), ('church', 'Christian Church'), ('gurdwara', 'Sikh Gurdwara'), ('synagogue', 'Jewish Synagogue'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
