# Generated by Django 5.2.5 on 2025-09-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_placecollection_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionplace',
            name='distance_from_previous',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
