# Generated by Django 5.2.5 on 2025-10-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_collectionplace_distance_from_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='placecollection',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='placecollection',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='collection_covers/'),
        ),
        migrations.AddField(
            model_name='placecollection',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
