# Generated by Django 5.2.5 on 2026-02-22 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_place_updated_by_alter_placeimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='placecollection',
            name='completion_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_reward', to='places.badge'),
        ),
        migrations.AddField(
            model_name='placecollection',
            name='required_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('place_added', 'Place Added'), ('place_approved', 'Place Approved'), ('place_rejected', 'Place Rejected'), ('comment_reply', 'Comment Reply'), ('nearby_place', 'Nearby Place'), ('challenge', 'Challenge'), ('badge_earned', 'Badge Earned'), ('welcome', 'Welcome'), ('welcome_back', 'Welcome Back')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.placecollection'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place'),
        ),
    ]
