# Generated by Django 5.2.5 on 2026-02-23 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_placecollection_completion_badge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionplace',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='collectionplace',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectionplace',
            name='place',
        ),
        migrations.RemoveField(
            model_name='placecollection',
            name='places',
        ),
        migrations.RemoveField(
            model_name='placecollection',
            name='category',
        ),
        migrations.RemoveField(
            model_name='placecollection',
            name='completion_badge',
        ),
        migrations.RemoveField(
            model_name='placecollection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_collection',
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='trail_covers/')),
                ('distance', models.FloatField(blank=True, null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='easy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_points', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(blank=True, related_name='trails', to='places.category')),
                ('completion_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trail_reward', to='places.badge')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='related_trail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.trail'),
        ),
        migrations.CreateModel(
            name='TrailFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'trail')},
            },
        ),
        migrations.CreateModel(
            name='TrailPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distance_from_previous', models.FloatField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.trail')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('trail', 'place')},
            },
        ),
        migrations.AddField(
            model_name='trail',
            name='places',
            field=models.ManyToManyField(related_name='trails', through='places.TrailPlace', to='places.place'),
        ),
        migrations.DeleteModel(
            name='CollectionFavorite',
        ),
        migrations.DeleteModel(
            name='CollectionPlace',
        ),
        migrations.DeleteModel(
            name='PlaceCollection',
        ),
    ]
