# Generated by Django 5.2.5 on 2025-10-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_collectionfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('explorer', 'Explorer'), ('contributor', 'Contributor'), ('social', 'Social'), ('special', 'Special')], default='explorer', max_length=20),
        ),
    ]
