# Generated by Django 5.2.5 on 2026-03-05 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_userchallengecompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text="FontAwesome class e.g. 'fas fa-utensils'", max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('duration_hours', models.DecimalField(decimal_places=1, help_text='Duration in hours, e.g. 9.5', max_digits=5)),
                ('price_lkr', models.DecimalField(decimal_places=2, help_text='Price per person in LKR', max_digits=10)),
                ('contact_numbers', models.TextField(blank=True, help_text='One phone number per line')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_packages', to=settings.AUTH_USER_MODEL)),
                ('offerings', models.ManyToManyField(blank=True, help_text='What is included in the tour', related_name='tour_packages', to='places.touroffering')),
                ('trails', models.ManyToManyField(blank=True, help_text='Select existing trails included in this tour', related_name='tour_packages', to='places.trail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
