# Generated by Django 5.2.5 on 2026-03-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_touroffering_tourpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='best_time_to_visit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
