# Generated by Django 5.2.5 on 2026-03-16 18:01

import places.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_place_best_time_to_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=places.models.badge_image_upload_to),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=places.models.place_image_upload_to),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(max_length=300, upload_to=places.models.place_extra_image_upload_to),
        ),
        migrations.AlterField(
            model_name='trail',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='trail_covers/'),
        ),
    ]
