# Generated by Django 5.2.5 on 2026-03-18 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_badge_image_alter_place_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='places.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'trail')},
            },
        ),
    ]
