# Generated by Django 5.2.5 on 2026-03-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_trailcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='ending_location',
            field=models.CharField(blank=True, help_text='Where the tour ends (leave blank if same as start)', max_length=255),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='event_date',
            field=models.DateField(blank=True, help_text='Date the tour takes place (leave blank if not a fixed-date event)', null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='event_time',
            field=models.TimeField(blank=True, help_text='Start time on the event date (optional)', null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='starting_location',
            field=models.CharField(blank=True, help_text="Where the tour begins, e.g. 'Colombo Fort Railway Station'", max_length=255),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='what_to_bring',
            field=models.TextField(blank=True, help_text="One item per line, e.g. 'Sunscreen\\nWater bottle\\nComfortable shoes'"),
        ),
        migrations.CreateModel(
            name='TourItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(help_text='1, 2, 3 …')),
                ('title', models.CharField(blank=True, help_text="Short title, e.g. 'Colombo to Kandy'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='What happens on this day')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, help_text='Approximate distance covered (optional)', max_digits=6, null=True)),
                ('highlights', models.TextField(blank=True, help_text="Comma-separated highlight tags, e.g. 'Sunrise view,Temple visit,Local lunch'")),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='places.tourpackage')),
            ],
            options={
                'ordering': ['tour', 'day_number'],
                'unique_together': {('tour', 'day_number')},
            },
        ),
    ]
