# Generated by Django 6.0.3 on 2026-03-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_tourpackage_ending_location_tourpackage_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='photo_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='trust_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('place_added', 'Place Added'), ('place_approved', 'Place Approved'), ('place_rejected', 'Place Rejected'), ('comment_reply', 'Comment Reply'), ('nearby_place', 'Nearby Place'), ('challenge', 'Challenge'), ('badge_earned', 'Badge Earned'), ('welcome', 'Welcome'), ('welcome_back', 'Welcome Back'), ('profile_complete', 'Profile Complete')], max_length=50),
        ),
    ]
