# Generated by Django 6.0.3 on 2026-03-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_remove_userprofile_website_userprofile_facebook_url_and_more'),
        ('places', '0019_seed_expert_areas'),
    ]

    operations = [
    ]
