"""
Django settings for ghostpin project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x0l3b9c*ogm8rymr5egpd2-6be^ayim)me9fuyc)e3(pmmf2l^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all hosts for development and deployment


# Application definition

INSTALLED_APPS = [
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pwa',
    'places',  # Our main app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ghostpin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add project-level templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',  
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ghostpin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# PWA Configuration
PWA_APP_NAME = 'GhostPin - Explore Historical Places'
PWA_APP_DESCRIPTION = 'Discover and explore historical places around the world'
PWA_APP_THEME_COLOR = '#4CAF50'  # Green theme color for the app
PWA_APP_BACKGROUND_COLOR = '#ffffff'  # White background
PWA_APP_ICONS = {
    'src': '/static/icons/icon-192x192.png',  # Path to the 192x192 icon
    'sizes': '192x192',
    'type': 'image/png',
}
PWA_APP_SIZES = ['192x192', '512x512']  # Icon sizes for various devices

PWA_APP_START_URL = '/'  # The URL the app starts with
PWA_APP_DISPLAY = 'standalone'  # Makes it behave like a native app (no browser UI)
PWA_APP_ORIENTATION = 'portrait-primary'  # Lock to portrait orientation
PWA_APP_SCOPE = '/'  # Define the scope of your app (root path is common)
PWA_APP_LANG = 'en'  # Language of the app
PWA_APP_CATEGORIES = ['travel', 'education', 'lifestyle']  # App categories

# The screenshots are optional but can be a nice touch.
PWA_APP_SCREENSHOTS = [
    {
        'src': '/static/icons/screenshot-mobile.png',
        'sizes': '390x844',
        'type': 'image/png',
        'form_factor': 'narrow',
    },
    {
        'src': '/static/icons/screenshot-desktop.png',
        'sizes': '1920x1080',
        'type': 'image/png',
        'form_factor': 'wide',
    },
]

# App Shortcuts (optional for quick links inside the app)
PWA_APP_SHORTCUTS = [
    {
        'name': 'Add New Place',
        'short_name': 'Add Place',
        'description': 'Submit a new historical place',
        'url': '/place/add/',
        'icons': [{'src': '/static/icons/icon-192x192.png', 'sizes': '192x192'}],
    }
]
